// apps/web-ar-admin/tools/endpoints/admin-read.ts
export interface Endpoint {
  method: 'GET' | 'POST';
  path: string;
  body?: Record<string, unknown>;
  idFrom?: {
    extractId: (data: any) => Record<string, unknown>;
    listPath: string;
  };
  /** Skip this endpoint during capture (unreachable service or backend has no data). Stub fixture kept as-is. */
  skip?: boolean;
}

// English camelCase keys — backend rejects the Chinese literals generated by gen-api
const ALL_DYNAMIC_KEYS = [
  'withdrawCategoryList',
  'organizationList',
  'tenantList',
  'sysCurrencyList',
  'payCodeList',
  'thirdPayMerchantList',
  'tenantPayChannelList',
  'sysPayChannelList',
  'rechargeCategoryList',
  'roleList',
  'menuList',
  'withdrawConfigGroupList',
];

export const ADMIN_READ_ENDPOINTS: Endpoint[] = [
  // ── Core auth ──────────────────────────────────────────────
  {
    method: 'POST',
    path: '/Login/Login',
    body: { userName: 'sys_milo', pwd: '12345678' },
  },
  { method: 'POST', path: '/Home/GetSysUserInfo', body: {} },
  { method: 'POST', path: '/Home/GetVersion', body: {} },
  { method: 'POST', path: '/Home/CheckHealth', body: {} },
  { method: 'POST', path: '/Login/HomeBasic', body: {} },
  // ── Auth/Common ────────────────────────────────────────────
  // skip: SIT returns code=11 "invalid param" for sys_milo — no auth context available
  { method: 'POST', path: '/Auth/CheckAuth', body: {}, skip: true },
  { method: 'POST', path: '/Auth/GetOrgTenantList', body: {} },
  { method: 'POST', path: '/Common/GetDictionary', body: {} },
  { method: 'POST', path: '/Common/GetPlatformDic', body: {} },
  { method: 'POST', path: '/SysDictionary/GetGroupData', body: {} },
  {
    method: 'POST',
    path: '/Common/GetDynamicDictionary',
    body: { keys: ALL_DYNAMIC_KEYS },
  },
  // skip: SIT returns code=14 "no permission" for sys_milo
  {
    method: 'POST',
    path: '/Common/GetDateTimeScopeTypes',
    body: {},
    skip: true,
  },
  { method: 'POST', path: '/Common/GetListBasicTable', body: {} },
  // skip: SIT returns code=7 "invalid param" — key 'SiteSetting' may not exist in SIT
  {
    method: 'POST',
    path: '/Common/GetSettingByKey',
    body: { key: 'SiteSetting' },
    skip: true,
  },
  {
    method: 'POST',
    path: '/Common/GetListRedisKey',
    body: { keyPattern: '*', redisDB: 'DB1', redisInstance: 'Admin' },
  },
  // ── System ─────────────────────────────────────────────────
  {
    method: 'POST',
    path: '/IpWhitelist/GetPageList',
    body: { pageNo: 1, pageSize: 20, orderBy: 'Desc' },
  },
  // skip: SIT returns code=14 "no permission" for sys_milo
  { method: 'POST', path: '/Menu/Get', body: { id: 0 }, skip: true },
  {
    method: 'POST',
    path: '/Role/GetPageList',
    body: { pageNo: 1, pageSize: 20, orderBy: 'Desc', sortField: 'id' },
  },
  // skip: SIT returned code=14 after env change; keep captured fixture
  {
    method: 'POST',
    path: '/SysDictionary/GetPageList',
    body: { pageNo: 1, pageSize: 20, orderBy: 'Desc' },
    skip: true,
  },
  {
    method: 'POST',
    path: '/SysLog/GetPageList',
    body: { pageNo: 1, pageSize: 20, orderBy: 'Desc' },
  },
  {
    method: 'POST',
    path: '/SysUsers/GetPageList',
    body: { pageNo: 1, pageSize: 20, orderBy: 'Desc' },
  },
  {
    method: 'POST',
    path: '/SysUsers/GetAdminPageList',
    body: { pageNo: 1, pageSize: 20, orderBy: 'Desc' },
  },
  // skip: SIT returned code=14 after env change; keep captured fixture
  {
    method: 'POST',
    path: '/SysUsers/GetTenantPageList',
    body: { pageNo: 1, pageSize: 20, orderBy: 'Desc' },
    skip: true,
  },
  // skip: SIT returns code=14 "no permission" for sys_milo
  {
    method: 'POST',
    path: '/SysUsers/GetSuperAuthUser',
    body: { orgId: 0 },
    skip: true,
  },
  // ── Tenant mgmt ────────────────────────────────────────────
  {
    method: 'POST',
    path: '/Country/GetPageList',
    body: { pageNo: 1, pageSize: 20, orderBy: 'Desc' },
  },
  // skip: SIT returns code=14 "no permission" for sys_milo even with valid countryCode
  {
    method: 'POST',
    path: '/Country/Get',
    idFrom: {
      listPath: '/Country/GetPageList',
      extractId: (d) => ({
        countryCode: d?.data?.list?.[0]?.countryCode ?? 'CN',
      }),
    },
    skip: true,
  },
  {
    method: 'POST',
    path: '/Currency/GetPageList',
    body: { pageNo: 1, pageSize: 20, orderBy: 'Desc' },
  },
  // skip: SIT returns code=14 "no permission" for sys_milo even with valid currencyCode
  {
    method: 'POST',
    path: '/Currency/Get',
    idFrom: {
      listPath: '/Currency/GetPageList',
      extractId: (d) => ({
        currencyCode: d?.data?.list?.[0]?.currencyCode ?? 'CNY',
      }),
    },
    skip: true,
  },
  {
    method: 'POST',
    path: '/Language/GetPageList',
    body: { pageNo: 1, pageSize: 20, orderBy: 'Desc' },
  },
  // skip: SIT returns code=14 "no permission" for sys_milo even with valid languageCode
  {
    method: 'POST',
    path: '/Language/Get',
    idFrom: {
      listPath: '/Language/GetPageList',
      extractId: (d) => ({
        languageCode: d?.data?.list?.[0]?.languageCode ?? 'zh-CN',
      }),
    },
    skip: true,
  },
  {
    method: 'POST',
    path: '/Organization/GetPageList',
    body: { pageNo: 1, pageSize: 20, orderBy: 'Desc' },
  },
  // Fixed: body now uses a valid id from the page list (was id:0 which is invalid)
  {
    method: 'POST',
    path: '/Organization/Get',
    idFrom: {
      listPath: '/Organization/GetPageList',
      extractId: (d) => ({ id: d?.data?.list?.[0]?.id ?? 1 }),
    },
  },
  {
    method: 'POST',
    path: '/Tenant/GetPageList',
    body: { pageNo: 1, pageSize: 20, orderBy: 'Desc' },
  },
  // skip: SIT returns code=14 "no permission" for sys_milo even with valid tenantId
  {
    method: 'POST',
    path: '/Tenant/GetV3Mode',
    idFrom: {
      listPath: '/Tenant/GetPageList',
      extractId: (d) => ({ tenantId: d?.data?.list?.[0]?.id ?? 1 }),
    },
    skip: true,
  },
  // ── Hub (separate microservice — not routed through admin URL) ─
  {
    method: 'POST',
    path: '/hub/domains/list',
    body: { page: 1, pageSize: 20 },
    skip: true,
  },
  {
    method: 'POST',
    path: '/hub/assets/list',
    body: { page: 1, pageSize: 20 },
    skip: true,
  },
  {
    method: 'POST',
    path: '/hub/jobs/list',
    body: { page: 1, pageSize: 20 },
    skip: true,
  },
  { method: 'POST', path: '/hub/jobs/stats', body: {}, skip: true },
  {
    method: 'POST',
    path: '/hub/job-logs/list',
    body: { page: 1, pageSize: 20 },
    skip: true,
  },
  { method: 'POST', path: '/hub/runners/list', body: {}, skip: true },
  {
    method: 'POST',
    path: '/hub/themes/list',
    body: { page: 1, pageSize: 20 },
    skip: true,
  },
  {
    method: 'POST',
    path: '/hub/layouts/list',
    body: { page: 1, pageSize: 20 },
    skip: true,
  },
  {
    method: 'POST',
    path: '/hub/tabbars/list',
    body: { page: 1, pageSize: 20 },
    skip: true,
  },
  { method: 'POST', path: '/hub/merchant/sites', body: {}, skip: true },
  { method: 'POST', path: '/hub/web/config', body: {}, skip: true },
  { method: 'POST', path: '/hub/web/game', body: {}, skip: true },
  {
    method: 'POST',
    path: '/hub/debug/scheduler/org-tenant-list',
    body: {},
    skip: true,
  },
  // ── Event (separate microservice — not routed through admin URL) ─
  { method: 'POST', path: '/event/metrics', body: {}, skip: true },
  { method: 'POST', path: '/event/options', body: {}, skip: true },
  { method: 'POST', path: '/event/admin/card-page', body: {}, skip: true },
  { method: 'POST', path: '/event/admin/project', body: {}, skip: true },
  { method: 'POST', path: '/event/admin/init/status', body: {}, skip: true },
  { method: 'POST', path: '/event/admin/alarm/stats', body: {}, skip: true },
  { method: 'POST', path: '/event/traffic/health', body: {}, skip: true },
  { method: 'POST', path: '/event/traffic/metrics', body: {}, skip: true },
  { method: 'POST', path: '/event/traffic/summary', body: {}, skip: true },
  { method: 'POST', path: '/event/traffic/trend', body: {}, skip: true },
  { method: 'POST', path: '/event/traffic/nodes', body: {}, skip: true },
  // ── AI (separate microservice — not routed through admin URL) ──
  { method: 'POST', path: '/ai/metrics', body: {}, skip: true },
  { method: 'POST', path: '/ai/health', body: {}, skip: true },
  { method: 'POST', path: '/ai/chat/config', body: {}, skip: true },
  {
    method: 'POST',
    path: '/ai/chat/sessions',
    body: { page: 1, pageSize: 20 },
    skip: true,
  },
  { method: 'POST', path: '/ai/knowledge/queue/stats', body: {}, skip: true },
  {
    method: 'POST',
    path: '/ai/knowledge/search',
    body: { q: 'test', limit: 5 },
    skip: true,
  },
  { method: 'POST', path: '/ai/admin/escalation/stats', body: {}, skip: true },
  { method: 'POST', path: '/ai/admin/feedback/stats', body: {}, skip: true },
  {
    method: 'POST',
    path: '/ai/report/sessions',
    body: { page: 1, pageSize: 10 },
    skip: true,
  },
  { method: 'POST', path: '/ai/report/alerts/config', body: {}, skip: true },
  {
    method: 'POST',
    path: '/ai/report/failed-queries',
    body: { page: 1, pageSize: 10 },
    skip: true,
  },
  { method: 'POST', path: '/ai/report/planner/stats', body: {}, skip: true },
];
