// apps/web-ar-admin/tools/endpoints/admin-read.ts
export interface Endpoint {
  method: 'GET' | 'POST';
  path: string;
  body?: Record<string, unknown>;
  idFrom?: {
    extractId: (data: any) => Record<string, unknown>;
    listPath: string;
  };
}

// English camelCase keys — backend rejects the Chinese literals generated by gen-api
const ALL_DYNAMIC_KEYS = [
  'withdrawCategoryList',
  'organizationList',
  'tenantList',
  'sysCurrencyList',
  'payCodeList',
  'thirdPayMerchantList',
  'tenantPayChannelList',
  'sysPayChannelList',
  'rechargeCategoryList',
  'roleList',
  'menuList',
  'withdrawConfigGroupList',
];

export const ADMIN_READ_ENDPOINTS: Endpoint[] = [
  // ── Core auth ──────────────────────────────────────────────
  {
    method: 'POST',
    path: '/Login/Login',
    body: { userName: 'sys_milo', pwd: '12345678' },
  },
  { method: 'GET', path: '/menu/all' },
  { method: 'GET', path: '/user/info' },
  { method: 'GET', path: '/auth/codes' },
  { method: 'POST', path: '/Home/GetSysUserInfo', body: {} },
  { method: 'POST', path: '/Home/GetVersion', body: {} },
  { method: 'POST', path: '/Home/CheckHealth', body: {} },
  { method: 'POST', path: '/Login/HomeBasic', body: {} },
  { method: 'GET', path: '/.well-known/openid-configuration' },
  // ── Auth/Common ────────────────────────────────────────────
  { method: 'POST', path: '/Auth/CheckAuth', body: {} },
  { method: 'POST', path: '/Auth/GetOrgTenantList', body: {} },
  { method: 'POST', path: '/Common/GetDictionary', body: {} },
  { method: 'POST', path: '/Common/GetPlatformDic', body: {} },
  { method: 'POST', path: '/SysDictionary/GetGroupData', body: {} },
  {
    method: 'POST',
    path: '/Common/GetDynamicDictionary',
    body: { keys: ALL_DYNAMIC_KEYS },
  },
  { method: 'POST', path: '/Common/GetDateTimeScopeTypes', body: {} },
  { method: 'POST', path: '/Common/GetListBasicTable', body: {} },
  {
    method: 'POST',
    path: '/Common/GetSettingByKey',
    body: { key: 'SiteSetting' },
  },
  {
    method: 'POST',
    path: '/Common/GetListRedisKey',
    body: { keyPattern: '*', redisDB: 'DB1', redisInstance: 'Admin' },
  },
  // ── System ─────────────────────────────────────────────────
  {
    method: 'POST',
    path: '/IpWhitelist/GetPageList',
    body: { pageNo: 1, pageSize: 20, orderBy: 'Desc' },
  },
  { method: 'POST', path: '/Menu/Get', body: { id: 0 } },
  {
    method: 'POST',
    path: '/Role/GetPageList',
    body: { pageNo: 1, pageSize: 20, orderBy: 'Desc', sortField: 'id' },
  },
  {
    method: 'POST',
    path: '/SysDictionary/GetPageList',
    body: { pageNo: 1, pageSize: 20, orderBy: 'Desc' },
  },
  {
    method: 'POST',
    path: '/SysLog/GetPageList',
    body: { pageNo: 1, pageSize: 20, orderBy: 'Desc' },
  },
  {
    method: 'POST',
    path: '/SysUsers/GetPageList',
    body: { pageNo: 1, pageSize: 20, orderBy: 'Desc' },
  },
  {
    method: 'POST',
    path: '/SysUsers/GetAdminPageList',
    body: { pageNo: 1, pageSize: 20, orderBy: 'Desc' },
  },
  {
    method: 'POST',
    path: '/SysUsers/GetTenantPageList',
    body: { pageNo: 1, pageSize: 20, orderBy: 'Desc' },
  },
  { method: 'POST', path: '/SysUsers/GetSuperAuthUser', body: { orgId: 0 } },
  // ── Tenant mgmt ────────────────────────────────────────────
  {
    method: 'POST',
    path: '/Country/GetPageList',
    body: { pageNo: 1, pageSize: 20, orderBy: 'Desc' },
  },
  { method: 'POST', path: '/Country/Get', body: {} },
  {
    method: 'POST',
    path: '/Currency/GetPageList',
    body: { pageNo: 1, pageSize: 20, orderBy: 'Desc' },
  },
  { method: 'POST', path: '/Currency/Get', body: {} },
  {
    method: 'POST',
    path: '/Language/GetPageList',
    body: { pageNo: 1, pageSize: 20, orderBy: 'Desc' },
  },
  { method: 'POST', path: '/Language/Get', body: {} },
  {
    method: 'POST',
    path: '/Organization/GetPageList',
    body: { pageNo: 1, pageSize: 20, orderBy: 'Desc' },
  },
  { method: 'POST', path: '/Organization/Get', body: { id: 0 } },
  {
    method: 'POST',
    path: '/Tenant/GetPageList',
    body: { pageNo: 1, pageSize: 20, orderBy: 'Desc' },
  },
  { method: 'POST', path: '/Tenant/GetV3Mode', body: { tenantId: 0 } },
  // ── Hub ────────────────────────────────────────────────────
  {
    method: 'POST',
    path: '/hub/domains/list',
    body: { page: 1, pageSize: 20 },
  },
  { method: 'POST', path: '/hub/assets/list', body: { page: 1, pageSize: 20 } },
  { method: 'POST', path: '/hub/jobs/list', body: { page: 1, pageSize: 20 } },
  { method: 'POST', path: '/hub/jobs/stats', body: {} },
  {
    method: 'POST',
    path: '/hub/job-logs/list',
    body: { page: 1, pageSize: 20 },
  },
  { method: 'POST', path: '/hub/runners/list', body: {} },
  { method: 'POST', path: '/hub/themes/list', body: { page: 1, pageSize: 20 } },
  {
    method: 'POST',
    path: '/hub/layouts/list',
    body: { page: 1, pageSize: 20 },
  },
  {
    method: 'POST',
    path: '/hub/tabbars/list',
    body: { page: 1, pageSize: 20 },
  },
  { method: 'POST', path: '/hub/merchant/sites', body: {} },
  { method: 'POST', path: '/hub/web/config', body: {} },
  { method: 'POST', path: '/hub/web/game', body: {} },
  { method: 'POST', path: '/hub/debug/scheduler/org-tenant-list', body: {} },
  // ── Event ──────────────────────────────────────────────────
  { method: 'POST', path: '/event/metrics', body: {} },
  { method: 'POST', path: '/event/options', body: {} },
  { method: 'POST', path: '/event/admin/card-page', body: {} },
  { method: 'POST', path: '/event/admin/project', body: {} },
  { method: 'POST', path: '/event/admin/init/status', body: {} },
  { method: 'POST', path: '/event/admin/alarm/stats', body: {} },
  { method: 'POST', path: '/event/traffic/health', body: {} },
  { method: 'POST', path: '/event/traffic/metrics', body: {} },
  { method: 'POST', path: '/event/traffic/summary', body: {} },
  { method: 'POST', path: '/event/traffic/trend', body: {} },
  { method: 'POST', path: '/event/traffic/nodes', body: {} },
  // ── AI Assistant ────────────────────────────────────────────
  { method: 'POST', path: '/ai/metrics', body: {} },
  { method: 'POST', path: '/ai/health', body: {} },
  { method: 'POST', path: '/ai/chat/config', body: {} },
  {
    method: 'POST',
    path: '/ai/chat/sessions',
    body: { page: 1, pageSize: 20 },
  },
  { method: 'POST', path: '/ai/knowledge/queue/stats', body: {} },
  {
    method: 'POST',
    path: '/ai/knowledge/search',
    body: { q: 'test', limit: 5 },
  },
  { method: 'POST', path: '/ai/admin/escalation/stats', body: {} },
  { method: 'POST', path: '/ai/admin/feedback/stats', body: {} },
  {
    method: 'POST',
    path: '/ai/report/sessions',
    body: { page: 1, pageSize: 10 },
  },
  { method: 'POST', path: '/ai/report/alerts/config', body: {} },
  {
    method: 'POST',
    path: '/ai/report/failed-queries',
    body: { page: 1, pageSize: 10 },
  },
  { method: 'POST', path: '/ai/report/planner/stats', body: {} },
];
