// apps/web-ar-admin/tools/endpoints/tenant-read.ts
import type { Endpoint } from './admin-read.js';

// English camelCase keys — backend rejects the Chinese literals generated by gen-api
const ALL_DYNAMIC_KEYS = [
  'withdrawCategoryList',
  'organizationList',
  'tenantList',
  'sysCurrencyList',
  'payCodeList',
  'thirdPayMerchantList',
  'tenantPayChannelList',
  'sysPayChannelList',
  'rechargeCategoryList',
  'roleList',
  'menuList',
  'withdrawConfigGroupList',
];

// Helpers for body shapes (tenant backend signs EXACTLY these fields)
const PAGE_T = {
  pageNo: 1,
  pageSize: 20,
  orderBy: 'Desc',
  tenantId: 0,
} as const;
const PAGE_NO_T = { pageNo: 1, pageSize: 20, orderBy: 'Desc' } as const;
// TypeList endpoints: zero-value pagination with tenantId
const TYPE_LIST = { pageNo: 0, pageSize: 0, orderBy: 0, tenantId: 0 } as const;

export const TENANT_READ_ENDPOINTS: Endpoint[] = [
  // ── Core auth ──────────────────────────────────────────────
  {
    method: 'POST',
    path: '/Login/Login',
    body: { userName: 'org_milo', pwd: '12345678' },
  },
  { method: 'GET', path: '/menu/all' },
  { method: 'GET', path: '/user/info' },
  { method: 'GET', path: '/auth/codes' },
  { method: 'POST', path: '/Home/GetSysUserInfo', body: {} },
  { method: 'POST', path: '/Login/HomeBasic', body: {} },
  // ── Auth/Common (no tenantId in signature for these) ──────
  { method: 'POST', path: '/Auth/CheckAuth', body: {} },
  { method: 'POST', path: '/Auth/GetOrgTenantList', body: {} },
  { method: 'POST', path: '/Common/GetDictionary', body: {} },
  { method: 'POST', path: '/Common/GetPlatformDic', body: {} },
  {
    method: 'POST',
    path: '/Common/GetDynamicDictionary',
    body: { keys: ALL_DYNAMIC_KEYS },
  },
  { method: 'POST', path: '/Common/GetDateTimeScopeTypes', body: {} },
  { method: 'POST', path: '/v1/Common/GetDictionary', body: {} },
  // ── Recharge (tenantId in signature) ──────────────────────
  {
    method: 'POST',
    path: '/RechargeCategory/GetPageList',
    body: { ...PAGE_T },
  },
  { method: 'POST', path: '/RechargeChannel/GetPageList', body: { ...PAGE_T } },
  {
    method: 'POST',
    path: '/RechargeLocalBank/GetPageList',
    body: { ...PAGE_T },
  },
  {
    method: 'POST',
    path: '/RechargeLocalEWallet/GetPageList',
    body: { ...PAGE_T },
  },
  {
    method: 'POST',
    path: '/RechargeLocalUpi/GetPageList',
    body: { ...PAGE_T },
  },
  {
    method: 'POST',
    path: '/RechargeLocalUsdt/GetPageList',
    body: { ...PAGE_T },
  },
  // ThirdPayMerchant does NOT include tenantId in signature
  {
    method: 'POST',
    path: '/ThirdPayMerchant/GetPageList',
    body: { ...PAGE_NO_T },
  },
  // ── Withdraw ──────────────────────────────────────────────
  {
    method: 'POST',
    path: '/WithdrawCategory/GetPageList',
    body: { ...PAGE_T },
  },
  { method: 'POST', path: '/WithdrawChannel/GetPageList', body: { ...PAGE_T } },
  // WithdrawConfigGroup does NOT include tenantId in signature
  {
    method: 'POST',
    path: '/WithdrawConfigGroup/GetPageList',
    body: { ...PAGE_NO_T },
  },
  {
    method: 'POST',
    path: '/WithdrawOrder/GetPageList',
    body: { ...PAGE_T, dateType: 0, sortField: 'CreateTime' },
  },
  {
    method: 'POST',
    path: '/WithdrawOrder/GetAuditPageList',
    body: { ...PAGE_T, dateType: 0, sortField: 'CreateTime' },
  },
  {
    method: 'POST',
    path: '/WithdrawRecord/GetPageList',
    body: { ...PAGE_T, sortField: 'CreateTime' },
  },
  // WithdrawStaticDay does NOT include tenantId in signature
  {
    method: 'POST',
    path: '/WithdrawStaticDay/GetPageList',
    body: { ...PAGE_NO_T },
  },
  // ── Report (no tenantId in signature) ─────────────────────
  {
    method: 'POST',
    path: '/PaymentReport/GetChannelPageList',
    body: { ...PAGE_NO_T },
  },
  {
    method: 'POST',
    path: '/PaymentReport/GetTenantPageList',
    body: { ...PAGE_NO_T },
  },
  // ── v1 Finance ─────────────────────────────────────────────
  {
    method: 'POST',
    path: '/v1/Finance/GetTabBanksPageList',
    body: { ...PAGE_T },
  },
  // ── v1 Users ───────────────────────────────────────────────
  {
    method: 'POST',
    path: '/v1/Users/GetUserPageList',
    body: { ...PAGE_T },
  },
  {
    method: 'POST',
    path: '/v1/Users/GetUserDetail',
    idFrom: {
      listPath: '/v1/Users/GetUserPageList',
      extractId: (d) => ({
        userId: d?.data?.list?.[0]?.id ?? d?.data?.list?.[0]?.userId ?? 1,
        tenantId: 0,
      }),
    },
  },
  {
    method: 'POST',
    path: '/v1/Users/GetUserBetTotal',
    idFrom: {
      listPath: '/v1/Users/GetUserPageList',
      // GetUserBetTotal uses zero-value pagination + tenantId
      extractId: (d) => ({
        userId: d?.data?.list?.[0]?.id ?? 1,
        pageNo: 0,
        pageSize: 0,
        orderBy: 0,
        tenantId: 0,
      }),
    },
  },
  {
    method: 'POST',
    path: '/v1/Users/GetUserBankCardPageList',
    idFrom: {
      listPath: '/v1/Users/GetUserPageList',
      extractId: (d) => ({
        userId: String(d?.data?.list?.[0]?.id ?? '1'),
        ...PAGE_T,
      }),
    },
  },
  {
    method: 'POST',
    path: '/v1/Users/GetUserRelativePageList',
    idFrom: {
      listPath: '/v1/Users/GetUserPageList',
      extractId: (d) => ({
        userId: String(d?.data?.list?.[0]?.id ?? '1'),
        ...PAGE_T,
      }),
    },
  },
  {
    method: 'POST',
    path: '/v1/Users/GetSubsetUserPageList',
    body: { ...PAGE_T },
  },
  {
    method: 'POST',
    path: '/v1/Users/GetOnlineUserPageList',
    body: { ...PAGE_T },
  },
  {
    method: 'POST',
    path: '/v1/Users/GetUPIPageList',
    idFrom: {
      listPath: '/v1/Users/GetUserPageList',
      extractId: (d) => ({
        userId: d?.data?.list?.[0]?.id ?? 1,
        ...PAGE_T,
      }),
    },
  },
  {
    method: 'POST',
    path: '/v1/Users/GetUserCpfPageList',
    idFrom: {
      listPath: '/v1/Users/GetUserPageList',
      extractId: (d) => ({
        userId: String(d?.data?.list?.[0]?.id ?? '1'),
        ...PAGE_T,
      }),
    },
  },
  {
    method: 'POST',
    path: '/v1/Users/GetUserRealNamePageList',
    idFrom: {
      listPath: '/v1/Users/GetUserPageList',
      extractId: (d) => ({
        userId: String(d?.data?.list?.[0]?.id ?? '1'),
        ...PAGE_T,
      }),
    },
  },
  {
    method: 'POST',
    path: '/v1/Users/GetUserUsdtPageList',
    idFrom: {
      listPath: '/v1/Users/GetUserPageList',
      extractId: (d) => ({
        userId: String(d?.data?.list?.[0]?.id ?? '1'),
        ...PAGE_T,
      }),
    },
  },
  {
    method: 'POST',
    path: '/v1/Users/GetUserWalletPageList',
    idFrom: {
      listPath: '/v1/Users/GetUserPageList',
      extractId: (d) => ({
        userId: String(d?.data?.list?.[0]?.id ?? '1'),
        ...PAGE_T,
      }),
    },
  },
  { method: 'POST', path: '/v1/Users/GetBankTypeList', body: { ...TYPE_LIST } },
  { method: 'POST', path: '/v1/Users/GetCpfTypeList', body: { ...TYPE_LIST } },
  { method: 'POST', path: '/v1/Users/GetUsdtTypeList', body: { ...TYPE_LIST } },
  {
    method: 'POST',
    path: '/v1/Users/GetWalletTypeList',
    body: { ...TYPE_LIST },
  },
  // ── v1 System logs ─────────────────────────────────────────
  {
    method: 'POST',
    path: '/v1/System/GetPlatformLogPageList',
    body: { ...PAGE_T },
  },
  {
    method: 'POST',
    path: '/v1/System/GetWebLogPageList',
    body: { ...PAGE_T },
  },
  // ── Hub (tenant has its own hub) ───────────────────────────
  {
    method: 'POST',
    path: '/hub/domains/list',
    body: { page: 1, pageSize: 20 },
  },
  { method: 'POST', path: '/hub/assets/list', body: { page: 1, pageSize: 20 } },
  { method: 'POST', path: '/hub/jobs/list', body: { page: 1, pageSize: 20 } },
  { method: 'POST', path: '/hub/jobs/stats', body: {} },
  { method: 'POST', path: '/hub/themes/list', body: { page: 1, pageSize: 20 } },
  {
    method: 'POST',
    path: '/hub/layouts/list',
    body: { page: 1, pageSize: 20 },
  },
  {
    method: 'POST',
    path: '/hub/tabbars/list',
    body: { page: 1, pageSize: 20 },
  },
  { method: 'POST', path: '/hub/merchant/sites', body: {} },
  { method: 'POST', path: '/hub/web/config', body: {} },
  // ── Event ──────────────────────────────────────────────────
  { method: 'POST', path: '/event/metrics', body: {} },
  { method: 'POST', path: '/event/traffic/health', body: {} },
  { method: 'POST', path: '/event/traffic/summary', body: {} },
  // ── AI ─────────────────────────────────────────────────────
  { method: 'POST', path: '/ai/metrics', body: {} },
  { method: 'POST', path: '/ai/health', body: {} },
];
